---
osd:
  drivers:
      nfs:
        server: "127.0.0.1"
        path: "/nfs"
#      aws:
#        aws_access_key_id: your_aws_access_key_id
#        aws_secret_access_key: your_aws_secret_access_key
