name: 'Mark stale issues PR that need review'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale-in-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been in review for 3 days with no activity.'
          only-pr-labels: stage/in-review
          days-before-stale: 3
          stale-pr-label: stage/in-review-stale
          days-before-pr-close: -1
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open for 180 days with no activity. Update this PR or it will be automatically closed in 6 months.'
          days-before-pr-stale: 90
          days-before-pr-close: 30
          stale-pr-label: lifecycle/stale
